### ISSUE TITLE
exporter questions

### ISSUE THREAD

**Issue by mjtrangoni** [tomcz/openldap_exporter#1]
Hi @tomcz,

I was taking a look at your exporter, and I am really interested in using it. 
There is some issues I wanted to clarify before with you. 

1. Why do you want to set the query interval at the exporter side?
```
  -interval duration
        Scrape interval (default 30s)
```
Prometheus set this at the server-side, otherwise you have one LDAP **scrape** time locally, and one **different** by every prometheus scrape. I mean, you should be querying LDAP simultaneously when prometheus scrapes the exporter target.

 2. Why did you put your code under `~/code/src/app` instead of '~/'? 

If you agree with those changes, I can start making some PR.

Thanks!

**Comment by tomcz** [comment]
1. Because I want to disconnect the exporter schedule from the prometheus schedule. I don't think it is a good idea to have the two linked. You clearly feel different, but I've seen prometheus flog systems mercilessly and I would prefer to have them disconnected.

2. This code is not a library, and does not need to abide by that standard, therefore it allows me to have the root of the project for documentation and scripts. Again, you feel different, but this works really well for me.
